### ISSUE TITLE
Tried to deploy Failed

### ISSUE THREAD

**Issue by tretelny** [aws-samples/aws-transcribe-captions-live#1]
Error: 

Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 0494f9d1-08ac-11e9-a90a-69cc4c3505b1)
--

**Comment by EddieGoynesAmazon** [comment]
I am looking into this.

**Comment by EddieGoynesAmazon** [comment]
This has been fixed. The problem was the permissions on the files didn't get pushed out to all regions. I fixxed this by using --acl public-read when syncing the AWS Lambda, and custom resources to the buckets in all regions.
