### ISSUE TITLE
special characters are not allowed

### ISSUE THREAD

**Issue by maobixiaoxin** [aws-samples/aws-transcribe-captions-live#10]
Error

Template validation error: Cannot parse template as YAML : special characters are not allowed

**Comment by maobixiaoxin** [comment]
I try to using your Cloudformation, And it does not work
-----------------------------------------------------------------------------------------------------
Error

Template validation error: Cannot parse template as YAML : special characters are not allowed

**Comment by EddieGoynesAmazon** [comment]
Hello there. I will take a look at this. A few questions. 

Which Yaml file are you using, the one in the repo, or the one linked to in the Readme file?
Which region are you launching this in?

**Comment by maobixiaoxin** [comment]
I try using both of them,
live-streaming-on-aws-no-cloudfront.yaml
live-streaming-on-aws.yaml

I am launching this in Tokyo and Oregon region

**Comment by EddieGoynesAmazon** [comment]
Hi, I am having trouble reproducing this error. 

How are you downloading the templates from GitHub? Are you cloning the repo. I had this error you describe if I copy and pasted the CloudFormation from GitHub directly into an empty cloudformation.yaml file on my computer.

**Comment by maobixiaoxin** [comment]
Hello,Eddie:
I download this file from this path:
aws-transcribe-captions-live/cloudformation/

![image](https://user-images.githubusercontent.com/35698134/53782894-62d88e80-3f4a-11e9-8ee7-e3cb3b240747.png)

**Comment by EddieGoynesAmazon** [comment]
Oh I see. So on GitHub if you try and download files like that it downloads the HTML website instead of the file. Try cloning the repo, downloading the zip file, or copy and paste the contents on the CloudFormation into a cloudformation.yaml file. That will fix your problem.

![image](https://user-images.githubusercontent.com/40248820/53790639-4c93e980-3edc-11e9-8339-0e85c99cd185.png)
