### ISSUE TITLE
Custom Vocabulary Transcribe

### ISSUE THREAD

**Issue by EddieGoynesAmazon** [aws-samples/aws-transcribe-captions-live#6]
Add Custom Vocabulary to the AWS Transcribe Streaming

**Comment by jremi** [comment]
@EddieGoynesAmazon Do you know if this be working? 

I used the AWS Console to upload a custom vocab list named `mycustomvocab`.... It was processed and says ready.

When i attempt to use the streaming AWS Transcribe WSS (websocket) and pass the query param `&vocabulary-name=mycustomvocab`... i get back the response:
```
The specified vocabulary doesn't exist. Check the name and try your request again.
```

Do custom vocabulary work in AWS Transcribe streaming mode?

**Comment by EddieGoynesAmazon** [comment]
Hi @jremi for your WSS (websocket) project that you are working on AWS Transcribe Streaming. Make sure to create the CustomVocabulary is in the same region that you are calling. 
Also make sure the CustomVocabulary doesn't fail compile when uploading in the AWS Console. 

Let me know if that fixes it.

**Comment by jremi** [comment]
@EddieGoynesAmazon .... Thanks for the prompt reply. Now that you mention the region .... It is very possible I may have had the wrong region set in the AWS web console and it's not matching the region i'm using on the wss connection. 

I will check and let you know. I appreciate ! 🙏
